Update the dependency to softwarerero:meteor-accounts-t9n for the npm…
meteor-compat/useraccounts-core pull request #2
Opened 2021-11-24 14:36 UTC by vparpoil

Following this [discussion](https://github.com/meteor/meteor/discussions/11743), a new proposition for the update of dependency, with a version bump 

This PR adds the npm package `meteor-accounts-t9n` as a dependency and expose globally the T9n object (which was the previous default behavior of T9n and remove the need to npm install `meteor-accounts-t9n` into the project )

2021-11-25 16:17 UTC, filipenevola requested changes
Is this 100% compatible with previous versions?

If that is the case please bump the minor version instead of the patch.

If that is not the case please list the possible breaking changes so we can analyze how to move forward.

2021-11-27 07:56 UTC, vparpoil commented
I don't see reasons for theses changes not to be 100% compatible, I hope I'm not mistaking.
T9n was exposed by  the former `softwarerero:accounts-t9n` so exposing it globally shouldn't be an issue. Also the package itself doesn't list breaking changes.
I bumped the version to 1.16.0

2021-12-06 17:44 UTC, filipenevola approved these changes

2021-12-06 17:44 UTC, merged

2021-12-06 17:45 UTC, filipenevola commented
Thanks @vparpoil .

Published useraccounts:core@1.16.0.           

Could you announce in the forums? Thanks.

2021-12-08 14:10 UTC, vparpoil commented
Done [here](https://forums.meteor.com/t/introducing-meteor-compat-packages/56759/11)
Thanks !